import { useState, ChangeEvent } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import useSWR from "swr";
import { calculateTimeAgo, fetcher } from "../utils";
import { ResponseFromAPI } from "../types";
import useDebounce from "../hooks/useDebounce";
import Loader from 'react-ts-loaders';

const Home: NextPage = () => {
  const [searchTerm, setSearchTerm] = useState("reactjs");
  const debouncedValue = useDebounce<string>(searchTerm, 500);

  const { data, isValidating, error } = useSWR(
    `https://hn.algolia.com/api/v1/search_by_date?query=${debouncedValue}`,
    fetcher
  );

  const handleChange = (event: ChangeEvent<HTMLInputElement>) => {
    setSearchTerm(event.target.value);
  };

  const renderContent = () => {
    if (!debouncedValue) {
      return <p>Please enter a search term</p>;
    }

    if (error) {
      return (
        <div className={styles.loadingState}>
          <h1>Something wrong happened</h1>
        </div>
      );
    }

    if (isValidating) {
      return (
        <Loader type="ripple"  color="rgba(116, 185, 255, 0.4)" />
      );
    }

    return (
      <div className={styles.grid}>
        {dataFromApi?.hits.map((item) => (
          <a
            className={styles.card}
            href={item.url ?? item.story_url}
            key={item.parent_id}
            target="_blank"
            rel="noreferrer"
          >
            <h2>{item.story_title || "Title not found"}</h2>
            <p>{item.author}</p>
            <p>{calculateTimeAgo(item.created_at)}</p>
          </a>
        ))}
      </div>
    );
  };

  const dataFromApi = data as ResponseFromAPI;

  return (
    <div className={styles.container}>
      <Head>
        <title>Contapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Contapp!</a>
        </h1>

        <div className={styles.formSearch}>
          <span>Search query: </span>
          <input
            className={styles.searchBox}
            type="text"
            placeholder="Search a topic of interest"
            value={searchTerm}
            onChange={handleChange}
          />
        </div>

        {renderContent()}
      </main>
    </div>
  );
};

export default Home;
